name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true
        type: string
  push:
    tags:
      - "v*"

jobs:
  release-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build binaries
        run: |
          make build-all-binaries
          ls -la 
          ls -la .build/
          ./package-github-binaries.sh
          ls -la dist/

      - name: Add binaries to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          allowUpdates: true
          omitBodyDuringUpdate: true

  build-and-push-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: falkordb/redis_exporter

      - name: Build and push scratch image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: scratch-release
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "TAG=${{ github.event.inputs.tag || github.ref_name }},SHA1=${{ github.sha }}"

      - name: Build and push alpine image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: alpine
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: falkordb/redis_exporter:${{ github.event.inputs.tag || github.ref_name }}-alpine,falkordb/redis_exporter:alpine
          labels: ${{ steps.meta.outputs.labels }}
          build-args: "TAG=${{ github.event.inputs.tag || github.ref_name }},SHA1=${{ github.sha }}"
